<html>
<head>
<title>
Voting system
</title>
<link rel="stylesheet" href="css/bootstrap.css" />
<link rel="stylesheet" href="mystyle.css"/>
<link rel="stylesheet" href="css/fonts.css" />
</head>
<body>

<div class="container">
	<div class="col-sm-6">

			<?php

			$id_generated="";

			$conn=new mysqli("localhost","root","","votingsystem_db");

			$id=$_GET['id'];

			$select="select * from id_request_tbl where id='$id'";

			$run=$conn->query($select);

			if($run->num_rows>0)
			{
				while($row=$run->fetch_array())
				{
					$user_aadhar=$row['user_aadhar'];
					$user_phonenumber=$row['user_phonenumber'];
				}

				$id_generated=mt_rand(0,getrandmax());


					?>


					<form method="post">
						<br>
						<br>
						<div class="form-group">
				          <label for="integer">Adhaar Number:</label>
				          <input type="integer" name="user_aadhar" class="form-control" required="true" value="<?php echo $user_aadhar;?>" readonly >
				        </div>

				        <div class="form-group">
				          <label for="integer">Phone Number(only 10 digits):</label>
				          <input type="integer" name="phonenumber" class="form-control" required="true" value="<?php echo $user_phonenumber;?>" readonly>
				        </div>


				         <div class="form-group">
				          <label for="integer">User ID generated by System:</label>
				          <input type="integer" name="user_id_generated" class="form-control" value="<?php echo $id_generated ; ?>" >
				        </div>

				        <div class="form-group">
				        	<input type="submit" name="update" value="Update User ID" class="form-control btn btn-success">
				        </div>
					</form>

					

				<?php
				

			}


			?>
	</div>

	<div class="col-sm-6">


	</div>

<?php
if(isset($_POST['update']))
{
 	$user_aadhar=$_POST['user_aadhar'];
	$user_id_generated=$_POST['user_id_generated'];
	$update="update users_db set user_id_generated='$user_id_generated' where user_aadhar='$user_aadhar'";
	$run=$conn->query($update);

	if($run)
		
		$delete="delete from id_request_tbl where user_aadhar='$user_aadhar'";
		$del=$conn->query($delete);
		if($del){
			header("Location: idrequest.php");
		}
		else{
		echo "<script>alert('Not Successfull!')</script>";
		}
}

?>


<script type="text/javascript" src="js/bootstrap.js" />
<script type="text/javascript" src="js/jquery.js" />

</body>
</html>


